### PR TITLE
Translations update from Lan2play Translate

### PR DESCRIPTION
**Pull request by lan2play-weblate**
Translations update from [Lan2play Translate](https://translate.lan2play.de) for [Eventula Manager/Eventula Manager about component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-about-component/).

It also includes following components:

* [Eventula Manager/Eventula Manager messages component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-messages-component/)

* [Eventula Manager/Eventula Manager legalnotice component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-legalnotice-component/)

* [Eventula Manager/Eventula Manager cookieconsent component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-cookieconsent-component/)

* [Eventula Manager/Eventula Manager events component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-events-component/)

* [Eventula Manager/Eventula Manager pagination component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-pagination-component/)

* [Eventula Manager/Eventula Manager passwords component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-passwords-component/)

* [Eventula Manager/Eventula Manager matchmaking component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-matchmaking-component/)

* [Eventula Manager/Eventula Manager help component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-help-component/)

* [Eventula Manager/Eventula Manager auth component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-auth-component/)

* [Eventula Manager/Eventula Manager payments component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-payments-component/)

* [Eventula Manager/Eventula Manager accounts component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-accounts-component/)

* [Eventula Manager/Eventula Manager tickets component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-tickets-component/)

* [Eventula Manager/Eventula Manager home component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-home-component/)

* [Eventula Manager/Eventula Manager terms component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-terms-component/)

* [Eventula Manager/Eventula Manager gallery component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-gallery-component/)

* [Eventula Manager/Eventula Manager layouts component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-layouts-component/)

* [Eventula Manager/Eventula Manager validation component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-validation-component/)

* [Eventula Manager/Eventula Manager news component](https://translate.lan2play.de/projects/eventula-manager/eventula-manager-news-component/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Apfelwurm** [comment]
@daurpam thank you very much! 
There is one open string (https://translate.lan2play.de/translate/eventula-manager/eventula-manager-accounts-component/es/?checksum=9d957bf01a3def59 ) that you maybe want to change, then its fully done :D

**Comment by daurpam** [comment]
Thank you @Apfelwurm, all open strings with the word "**token**" involved could be set as original in english. The translation has no too much sense in spanish!
Regards

**Comment by Apfelwurm** [comment]
Was this also the case with `Tickets`? :D then i maybe made a mistake with my "fix" and i have to reset that again as well. Im going to overwrite the failed checks then, so it will show 100% afterwards. If you plan to do something with eventula that is more advanced, get in contact with me cause you will need help (especially with get5) cause the docs are not finished yet.

**Comment by daurpam** [comment]
> Was this also the case with `Tickets`? :D 
Sure!

> If you plan to do something with eventula that is more advanced....

Ok, perhaps in next week. We had our first event using eventula next weekend, and need to test lot of things.
Thank you!

**Comment by Apfelwurm** [comment]
okay thanks, so i'll revert that change :D 

Oh okay, test everything well before you use this for running your event, its not as easy as you might hope :D 

You can hmu on DC (Apfelwurm#5627) anytime, if you need help.

**Pull request merged**
